server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/local_account_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

stripe:
  api:
    secret: sk_test_51TNUAID6dRsyPGgsJUZq8mnY4NYBPzUd24IE6ICvqqTigkx2SWrdQIEfZVswrYF6Tev6HJkgzRMlSL3oNs5pHc0Z00ll1kGGZV
  webhook:
    secret:  whsec_b2196b210408efb2dab3fdad7bf50871c623729a3a0470a804327b80e1051cec

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.lovable-core.svc.cluster.local:5432/account_db
    username: account_user
    password: ${ACCOUNT_DB_PASSWORD}


stripe:
  api:
    secret: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}
